project:
  name: quickstart-ibm-websphere-liberty
  owner: susarlam@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  quickstart-ibm-websphere-liberty:
    parameters:
      ALBSSLCertificateARN: ''
      AvailabilityZones: $[alfred_genaz_2]
      BastionAMIOS: Amazon-Linux-HVM
      BastionInstanceType: t2.micro
      CloudFrontACMCertificateARN: ''
      CreateCloudFrontDistribution: 'Yes'
      DeploySampleApp: 'No'
      HostedZoneName: ''
      KeyPairName: $[alfred_getkeypair]
      LibertyInstanceType: t2.large
      LibertyNodesDesiredCapacity: '2'
      LibertyNodesMaxSize: '4'
      LibertyNodesMinSize: '2'
      OperatorEmail: foo@example.com
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RemoteAccessCIDR: 10.0.0.0/16
      VPCCIDR: 10.0.0.0/16
    regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    s3_bucket: ''
    template: templates/liberty-master.template.yaml
